### ISSUE TITLE
ImportError: No module named Math

### ISSUE THREAD

**Issue by jishuzhain** [TheSph1nx/AbsoluteZero#1]
1877 INFO: Loading module hooks...
1878 INFO: Loading module hook "hook-encodings.py"...
2460 INFO: Loading module hook "hook-Crypto.py"...
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ImportError: No module named Math
2518 INFO: Looking for ctypes DLLs
2518 INFO: Analyzing run-time hooks ...
2523 INFO: Looking for dynamic libraries

The generated exe file is not work

**Comment by jishuzhain** [comment]
run backdoor.exe false:

Traceback (most recent call last):
  File "backdoor.py", line 12, in <module>
  File "<string>", line 4, in <module>
ImportError: No module named platform
[7436] Failed to execute script backdoor

**Comment by jishuzhain** [comment]
PS C:\Python27\Lib\site-packages\PyInstaller> pyinstaller.exe --version
3.5

**Comment by TheSph1nx** [comment]
I think this is a Python Fault because I've tested it on more machines and I always compile it. Try to uninstall pyinstaller and install it again or even your Python version and be sure to install all the requirements .

**Comment by jishuzhain** [comment]
> I think this is a Python Fault because I've tested it on more machines and I always compile it. Try to uninstall pyinstaller and install it again or even your Python version and be sure to install all the requirements .

ok，I will try
